title: Home infra
description: Documentation about my home infrastructure

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true
  remove_originals: true

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-mentions