title: Twan's Home infra
description: Documentation about my home infrastructure

remote_theme: pmarsceill/just-the-docs

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE

plugins:
  - jekyll-seo-tag
  